# Generated by Django 4.2.5 on 2023-09-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='car_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
