# Generated by Django 4.2.5 on 2023-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurantcategory_restaurant_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcategory',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
